version: "3.7"

services:
  movie-app:
    container_name: movie-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    env_file: .env
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
